image: node:latest

cache:
  paths:
    - node_modules

.build_package:
  script:
    - export SOURCE_DATE_EPOCH=$(git log -1 --pretty=%ct)
    - npm install
    - npm run clean build package

build:
  extends: .build_package
  stage: build
  artifacts:
    expire_in: 1 week
    paths:
      - dist
  except:
    - master

release:
  extends: .build_package
  stage: deploy
  artifacts:
    paths:
      - dist
  only:
    - master
